---
- name: Install a list of packages 
  hosts: vm
  become: true
  gather_facts: false
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /opt/foo.conf
        dest: /etc/foo.conf
        owner: root
        group: root
        mode: '0644'
...