---
- name: Install a list of packages 
  hosts: aws
  become: true
  gather_facts: false
  tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
    
    - name: Install a list of packages
      apt:
        pkg:
          - net-tools
          - firewalld
          - apache2
        state: present
...