---
- name: Install a list of packages 
  hosts: aws
  become: true
  gather_facts: false
  tasks:
    - name: Start service httpd, if not started
      service:
        name: apache2
        state: started
...